routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Auth::routes();

Route::group(['prefix' => 'backend', 'middleware' => 'auth'], function () {

    Route::view('/', 'backend.index');
    Route::resource('projects', 'Auth\ProjectController', ['except' => 'show']);
    Route::resource('vacancys', 'Auth\VacancyController', ['except' => 'show']);

    Route::group(['prefix' => 'leads'], function () {
        Route::get('/', 'Auth\LeadController@index')->name('leads.index');
        Route::get('{lead}', 'Auth\LeadController@show')->name('leads.show');
        Route::delete('{lead}', 'Auth\LeadController@destroy')->name('leads.destroy');
    });
});

Route::get('/promotion/lead/', 'frontend\PageController@lead');

Route::get('/quiz-site', 'frontend\PageController@quizSite');
Route::get('/quiz-promo', 'frontend\PageController@quizPromo');
Route::get('/quiz-promo2', 'frontend\PageController@quizPromo2');
Route::get('/{any}', 'frontend\PageController@app')->where('any', '.*');

Route::post('/leads', 'Auth\LeadController@store')->name('leads.store');

app/Lead.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Lead extends Model
{
    protected $fillable = [
        'name', 'phone', 'text', 'tag' 
    ]; 
}

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    public $timestamps = false;
    
    protected $fillable = [
        'title', 'status', 'img', 'url', 'description'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Vacancy.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vacancy extends Model
{
    protected $table = 'vacancys';

    public $timestamps = false;
    
    protected $fillable = [
        'title', 'status', 'linck_hh', 'description'
    ];
}

app/Visit.php
<? 
namespace App;

class Visit {
	public function __construct () {
		$visits = [];
		$visits = session('visits');

		$referer = $_SERVER['HTTP_REFERER'] ?? '';

		$visits[] = [
				'referer'	    =>	    $referer,
				'page'	        =>	    url(request()->url()),
				'utm_source'	=>		request()->get('utm_source'),
				'utm_medium'	=>		request()->get('utm_medium'),
				'utm_campaign'	=>		request()->get('utm_campaign'),
				'utm_term'	    =>	    request()->get('utm_term'),
				'time'	        =>	    date('Y-m-d H:i:s')
		];
		session(['visits' => $visits]);

		$data = json_encode(session('visits'));
		// echo "<script>console.log({$data})</script>";

	}
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/frontend/PageController.php
<?php

namespace App\Http\Controllers\frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\Project;
use App\Vacancy;
use App\Visit;
use Carbon\Carbon;

class PageController extends Controller
{
    public function app(Request $request) {

        $offerExpire = '';
        $offerExtensionDay = 25;
        $today = Carbon::now();

        //date change after offerExtensionDay
        if($today->day >= $offerExtensionDay) {
            $lastDay = $today->modify('1 month')->endOfMonth()->day;
        } else {
            $lastDay = $today->endOfMonth()->day;
        };
        $monthLocal = '';
        //next month code
        switch($today->format('M')) {
            case 'Jan': $monthLocal = 'января'; break;
            case 'Feb': $monthLocal = 'февраля'; break;
            case 'Mar': $monthLocal = 'марта'; break;
            case 'Apr': $monthLocal = 'апреля'; break;
            case 'May': $monthLocal = 'мая'; break;
            case 'Jun': $monthLocal = 'июня'; break;
            case 'Jul': $monthLocal = 'июля'; break;
            case 'Aug': $monthLocal = 'августа'; break;
            case 'Sep': $monthLocal = 'сентября'; break;
            case 'Oct': $monthLocal = 'октября'; break;
            case 'Nov': $monthLocal = 'ноября'; break;
            case 'Dec': $monthLocal = 'декабря'; break;
            default: break;
        }
        $offerExpire = $lastDay.' '.$monthLocal;
        // dd($offerExpire);

        return view('layouts.site',['offerExpire' => $offerExpire]);
    }

    public function quizSite(Request $request) {

        return view('layouts.quiz_site');
    }

    public function quizPromo(Request $request) {

        return view('layouts.quiz_promo');
    }

    public function quizPromo2(Request $request) {

        return view('layouts.quiz_promo2');
    }

    public function spa(Request $request) {

        return [
            'projects' => Project::where('status', 'active')->get(),
            'vacancys' => Vacancy::where('status', 'active')->get()
        ];
    }

    public function lead(){
        return view('layouts.lead');
    }

}

resources/views/backend/footer.blade.php
<footer class="bdT ta-c p-30 lh-0 fsz-sm c-grey-600"><span>Copyright © 2017 Designed by <a href="https://colorlib.com" target="_blank" title="Colorlib">Colorlib</a>. All rights reserved.</span></footer>

resources/views/backend/header.blade.php
<div class="header navbar">
    <div class="header-container">
        <ul class="nav-left">
            <li><a id="sidebar-toggle" class="sidebar-toggle" href="javascript:void(0);"><i class="ti-menu"></i></a></li>
        </ul>
        <ul class="nav-right">
            <li>
                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                    {{ __('Logout') }}
                </a>
            </li>
        </ul>
    </div>
</div>

resources/views/backend/index.blade.php
@extends('layouts.admin')


@section('sidebar')

    @include('backend.sidebar')  

@endsection

@section('content')

    <div class="page-container">  
      
        @include('backend.header')

        <main class="main-content bgc-grey-100">
            <div id="mainContent">
              
               @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif
                
                @yield('section')
            </div>
        </main>

        @include('backend.footer')
    
    </div>

@endsection

resources/views/backend/lead/index.blade.php
@extends('backend.index')

@section('section')

<div class="container-fluid">
    <h4 class="c-grey-900 mT-10 mB-30">{{$title}}</h4>

    <div class="row">
        <div class="col-md-12">
            <div class="bgc-white bd bdrs-3 p-20 mB-20">

                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Имя</th>
                            <th scope="col">Телефон</th>
                            <th scope="col">Тег</th>
                            <th scope="col">Дата</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    
                    <tbody>
                       @foreach($leads as $lead)
                            <tr>
                                <th scope="row">{{ $lead->id }}</th>
                                <td>{{ $lead->name }}</td>
                                <td>{{ $lead->phone}}</td>
                                <td>{{ $lead->tag }}</td>
                                <td>{{ $lead->created_at }}</td>
                                <td>

                                    {!! Form::open(['url' => route('leads.destroy',['lead'=>$lead->id]),'class'=>'text-right  gap-10','method'=>'POST']) !!}

                                    {{ method_field('DELETE') }}

                                    {!! Form::button('Удалить', ['class' => 'btn cur-p btn-outline-danger','type'=>'submit']) !!}

                                    {!! Html::link(route('leads.show',['lead'=>$lead->id]),'Посмотреть',['class'=>'btn cur-p btn-outline-primary']) !!}

                                    {!! Form::close() !!}

                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>

@endsection

resources/views/backend/lead/show.blade.php
@extends('backend.index') 
@section('section')

<div class="row">

    <div class="col-sm-12 form-row mT-10 mB-10">
        <h4 class="col-sm-6 c-grey-900">{{$title}}</h4>
        <div class="text-right col-sm-6">
        
            {!! Html::link(route('leads.index'),'Вернуться к списку',['class'=>'btn cur-p btn-secondary']) !!}
            
        </div>
    </div>

    <div class="col-sm-12 mT-20">
        <div class="bgc-white p-20 bd">
            <div class="mT-30">
                <div class="form-row">
                    <div class="form-group col-md-12">
                        {{ Form::label('tag', 'Название формы') }}
                        <div class="form-control">{{ $lead->tag }}</div> 
                    </div>
                    <div class="form-group col-md-6">
                        {{ Form::label('name', 'Имя') }} 
                        <div class="form-control">{{ $lead->name }}</div> 
                    </div>
                    <div class="form-group col-md-6">
                        {{ Form::label('phone', 'Телефон') }} 
                        <div class="form-control">{{ $lead->phone }}</div> 
                    </div>
                </div>
            </div>
            @if (isset($lead->text))
            <div class="form-row mT-30">
                <div class="form-group col-md-12">
                    {{ Form::label('text', 'Текст') }}
                    {{ Form::textarea('text', $lead->text, array('class' => 'form-control', 'readonly')) }}
                </div>
            </div>
            @endif
        </div>
    </div>

</div>


@endsection

resources/views/backend/project/create.blade.php
@extends('backend.index') 
@section('section')

{!! Form::open(['url' => route('projects.store'), 'class'=>'row', 'method'=>'POST','enctype'=>'multipart/form-data']) !!}

<div class="col-sm-12 form-row mT-10 mB-10">
    <h4 class="col-sm-6 c-grey-900">{{$title}}</h4>
    <div class="text-right col-sm-6">
       
        {!! Html::link(route('projects.index'),'Вернуться к списку',['class'=>'btn cur-p btn-secondary']) !!}
        {{ Form::submit('Сохранить', array('class' => 'btn btn-primary')) }}
        
    </div>
</div>

<div class="col-sm-12 mT-20">
    <div class="bgc-white p-20 bd">
        <div class="mT-30">
            <div class="form-row">
                <div class="form-group col-md-8">
                    {{ Form::label('title', 'Название') }} 
                    {{ Form::text('title', null, array('class'=>'form-control')) }}
                </div>
                <div class="form-group col-md-4">
                    {{ Form::label('status', 'Статус') }}
                    {!! Form::select('status', array('active' => 'Активно', 'deactived' => 'Скрыто'), null,  array('class' => 'form-control')) !!} 
                </div>
                <div class="form-group col-md-6">
                    {{ Form::label('url', 'Ссылка') }} 
                    {{ Form::text('url', null, array('class'=>'form-control')) }} 
                </div>
            </div>
            <div class="form-row mT-30">
                <div class="form-group col-md-12">
                    {{ Form::label('description', 'Описание проекта') }}
                    {{ Form::textarea('description', null, array('class' => 'form-control')) }}
                </div>
            </div>
         
        </div>
    </div>
</div>

<div class="col-sm-12 mT-20">
    <div class="bgc-white p-20 bd">
        <div class="mT-30">
            <div class="form-row">
                <div class="col-md-12">
                    <div class="bgc-white p-20 bd">
                        <div class="mT-30">
                            <div class="form-group">
                                {{ Form::label('img', 'Изображение') }}
                                {!! Form::file('img', array('class' => 'general-img')) !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{!! Form::close() !!}


@endsection

resources/views/backend/project/edit.blade.php
@extends('backend.index') 
@section('section')

{!! Form::open(['url' => route('projects.update',array('project'=>$data['id'])), 'class'=>'row', 'method'=>'POST','enctype'=>'multipart/form-data']) !!} 
{!! Form::hidden('_method', 'patch') !!} 
{!! Form::hidden('id', $data['id']) !!}

<div class="col-sm-12 form-row mT-10 mB-10">
    <h4 class="col-sm-6 c-grey-900">{{$title}}</h4>
    <div class="text-right col-sm-6">
       
        {!! Html::link(route('projects.index'),'Вернуться к списку',['class'=>'btn cur-p btn-secondary']) !!}
        {{ Form::submit('Сохранить', array('class' => 'btn btn-primary')) }}
        
        
    </div>
</div>

<div class="col-sm-12 mT-20">
    <div class="bgc-white p-20 bd">
        <div class="mT-30">
            <div class="form-row">
                <div class="form-group col-md-8">
                    {{ Form::label('title', 'Название') }} 
                    {{ Form::text('title', $data['title'], array('class'=>'form-control')) }}
                </div>
                <div class="form-group col-md-4">
                    {{ Form::label('status', 'Статус') }}
                    {!! Form::select('status', array('active' => 'Активно', 'deactived' => 'Скрыто'), $data['status'],  array('class' => 'form-control')) !!} 
                </div>
                <div class="form-group col-md-6">
                    {{ Form::label('url', 'Ссылка') }} 
                    {{ Form::text('url', $data['url'], array('class'=>'form-control')) }} 
                </div>
            </div>
            <div class="form-row mT-30">
                <div class="form-group col-md-12">
                    {{ Form::label('description', 'Описание проекта') }}
                    {{ Form::textarea('description', $data['description'], array('class' => 'form-control')) }}
                </div>
            </div>
         
        </div>
    </div>
</div>

<div class="col-sm-12 mT-20">
    <div class="bgc-white p-20 bd">
        <div class="mT-30">
            <div class="form-row">
                <div class="col-md-12">
                    <div class="bgc-white p-20 bd">
                        <div class="mT-30">
                            <div class="form-group">
                                {{ Form::label('img', 'Изображение') }}
                                {!! Form::file('img', array('class' => 'general-img', 'data-fileuploader-listInput' => 'general_photo', 'data-fileuploader-files' => $preLoadImg[0])) !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{!! Form::close() !!}

@endsection

resources/views/backend/project/index.blade.php
@extends('backend.index')

@section('section')

<div class="container-fluid">
    <h4 class="c-grey-900 mT-10 mB-30">{{$title}}</h4>

    <div class="row">
        <div class="col-md-12">
            <div class="bgc-white bd bdrs-3 p-20 mB-20">

                <div class="text-right form-group">
                    <a href="{{ route('projects.create') }}" class="btn cur-p btn-primary">Создать</a>
                </div>

                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Название</th>
                            <th scope="col">Статус</th>
                            <th scope="col">URL</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    
                    <tbody>
                       @foreach($projects as $project)
                            <tr {!! $project->status === 'deactived' ? 'style="background-color: rgba(0,0,0,.05);}"' : '' !!}>
                                <th scope="row">{{ $project->id }}</th>
                                <td>{{ $project->title }}</td>
                                <td>{{ $project->status}}</td>
                                <td>
                                    @if (isset($project->url))
                                        {{ $project->url }}
                                    @endif
                                </td>
                                <td>

                                    {!! Form::open(['url' => route('projects.destroy',['project'=>$project->id]),'class'=>'text-right  gap-10','method'=>'POST']) !!}

                                    {{ method_field('DELETE') }}

                                    {!! Form::button('Удалить', ['class' => 'btn cur-p btn-outline-danger','type'=>'submit']) !!}

                                    {!! Html::link(route('projects.edit',['project'=>$project->id]),'Редактировать',['class'=>'btn cur-p btn-outline-primary']) !!}

                                    {!! Form::close() !!}

                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>

@endsection

resources/views/backend/sidebar.blade.php
<div class="sidebar">
    <div class="sidebar-inner">
        <div class="sidebar-logo">
            <div class="peers ai-c fxw-nw">
                <div class="peer peer-greed">
                    <a class="sidebar-link td-n" href="/">
                        <div class="peers ai-c fxw-nw">
                            <div class="peer">
                                <div class="logo"><img src="{{ asset('img/gui/logo_square.svg') }}" alt="trend-pro"></div>
                            </div>
                            <div class="peer peer-greed">
                                <h5 class="lh-1 mB-0 logo-text">Перейти на сайт</h5>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="peer">
                    <div class="mobile-toggle sidebar-toggle"><a href="" class="td-n"><i class="ti-arrow-circle-left"></i></a></div>
                </div>
            </div>
        </div>
        <ul class="sidebar-menu scrollable pos-r">
            <li class="nav-item mT-30">
                <a href="{{ route('projects.index') }}" class="sidebar-link">
                    <span class="icon-holder">
                        <i class="c-blue-500 ti-files"></i> 
                    </span>
                    <span class="title">Портфолио</span>
                </a>
            </li>
            <li class="nav-item mT-30">
                <a href="{{ route('leads.index') }}" class="sidebar-link">
                    <span class="icon-holder">
                        <i class="c-blue-500 ti-files"></i> 
                    </span>
                    <span class="title">Заявки</span>
                </a>
            </li>
            <li class="nav-item mT-30">
                <a href="{{ route('vacancys.index') }}" class="sidebar-link">
                    <span class="icon-holder">
                        <i class="c-blue-500 ti-files"></i> 
                    </span>
                    <span class="title">Вакансии</span>
                </a>
            </li>
        </ul>
    </div>
</div>

resources/views/backend/vacancy/create.blade.php
@extends('backend.index') 
@section('section')

{!! Form::open(['url' => route('vacancys.store'), 'class'=>'row', 'method'=>'POST','enctype'=>'multipart/form-data']) !!}

<div class="col-sm-12 form-row mT-10 mB-10">
    <h4 class="col-sm-6 c-grey-900">{{$title}}</h4>
    <div class="text-right col-sm-6">
       
        {!! Html::link(route('vacancys.index'),'Вернуться к списку',['class'=>'btn cur-p btn-secondary']) !!}
        {{ Form::submit('Сохранить', array('class' => 'btn btn-primary')) }}
        
    </div>
</div>

<div class="col-sm-12 mT-20">
    <div class="bgc-white p-20 bd">
        <div class="mT-30">
            <div class="form-row">
                <div class="form-group col-md-8">
                    {{ Form::label('title', 'Название') }} 
                    {{ Form::text('title', null, array('class'=>'form-control')) }}
                </div>
                <div class="form-group col-md-4">
                    {{ Form::label('status', 'Статус') }}
                    {!! Form::select('status', array('active' => 'Активно', 'deactived' => 'Скрыто'), null,  array('class' => 'form-control')) !!} 
                </div>
                <div class="form-group col-md-6">
                    {{ Form::label('linck_hh', 'Ссылка на вакансию') }} 
                    {{ Form::text('linck_hh', null, array('class'=>'form-control')) }} 
                </div>
            </div>
            <div class="form-row mT-30">
                <div class="form-group col-md-12">
                    {{ Form::label('description', 'Описание') }}
                    {{ Form::textarea('description', null, array('class' => 'form-control')) }}
                </div>
            </div>
         
        </div>
    </div>
</div>

{!! Form::close() !!}


@endsection

resources/views/backend/vacancy/edit.blade.php
@extends('backend.index') 
@section('section')

{!! Form::open(['url' => route('vacancys.update',array('vacancy'=>$data['id'])), 'class'=>'row', 'method'=>'POST','enctype'=>'multipart/form-data']) !!} 
{!! Form::hidden('_method', 'patch') !!} 
{!! Form::hidden('id', $data['id']) !!}

<div class="col-sm-12 form-row mT-10 mB-10">
    <h4 class="col-sm-6 c-grey-900">{{$title}}</h4>
    <div class="text-right col-sm-6">
       
        {!! Html::link(route('vacancys.index'),'Вернуться к списку',['class'=>'btn cur-p btn-secondary']) !!}
        {{ Form::submit('Сохранить', array('class' => 'btn btn-primary')) }}
        
        
    </div>
</div>

<div class="col-sm-12 mT-20">
    <div class="bgc-white p-20 bd">
        <div class="mT-30">
            <div class="form-row">
                <div class="form-group col-md-8">
                    {{ Form::label('title', 'Название') }} 
                    {{ Form::text('title', $data['title'], array('class'=>'form-control')) }}
                </div>
                <div class="form-group col-md-4">
                    {{ Form::label('status', 'Статус') }}
                    {!! Form::select('status', array('active' => 'Активно', 'deactived' => 'Скрыто'), $data['status'],  array('class' => 'form-control')) !!} 
                </div>
                <div class="form-group col-md-6">
                    {{ Form::label('linck_hh', 'Ссылка на вакансию') }} 
                    {{ Form::text('linck_hh', $data['linck_hh'], array('class'=>'form-control')) }} 
                </div>
            </div>
            <div class="form-row mT-30">
                <div class="form-group col-md-12">
                    {{ Form::label('description', 'Описание проекта') }}
                    {{ Form::textarea('description', $data['description'], array('class' => 'form-control')) }}
                </div>
            </div>
         
        </div>
    </div>
</div>

{!! Form::close() !!}

@endsection

resources/views/backend/vacancy/index.blade.php
@extends('backend.index')

@section('section')

<div class="container-fluid">
    <h4 class="c-grey-900 mT-10 mB-30">{{$title}}</h4>

    <div class="row">
        <div class="col-md-12">
            <div class="bgc-white bd bdrs-3 p-20 mB-20">

                <div class="text-right form-group">
                    <a href="{{ route('vacancys.create') }}" class="btn cur-p btn-primary">Создать</a>
                </div>

                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Название</th>
                            <th scope="col">Статус</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    
                    <tbody>
                       @foreach($vacancys as $vacancy)
                            <tr {!! $vacancy->status === 'deactived' ? 'style="background-color: rgba(0,0,0,.05);}"' : '' !!}>
                                <th scope="row">{{ $vacancy->id }}</th>
                                <td>{{ $vacancy->title }}</td>
                                <td>{{ $vacancy->status}}</td>
                                <td>

                                    {!! Form::open(['url' => route('vacancys.destroy',['vacancy'=>$vacancy->id]),'class'=>'text-right  gap-10','method'=>'POST']) !!}

                                    {{ method_field('DELETE') }}

                                    {!! Form::button('Удалить', ['class' => 'btn cur-p btn-outline-danger','type'=>'submit']) !!}

                                    {!! Html::link(route('vacancys.edit',['vacancy'=>$vacancy->id]),'Редактировать',['class'=>'btn cur-p btn-outline-primary']) !!}

                                    {!! Form::close() !!}

                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>

@endsection

resources/views/frontend/banner.blade.php
<section class="hero" ref="infoBox">
    <div class="hero__wrapper">
        <div class="hero__items">
            <div class="hero__items_item">
                <p class="hero_intro">Без предоплаты</p>
                <h1 class="hero_title">Создание и продвижение сайтов в Москве</h1>
                <p class="hero_subtitle">Давайте создавать невероятные сайты вместе. Настало время действовать.</p>
                <form-component button="Выбрать проект" tag="Главный баннер"></form-component>
            </div>
        </div>
    </div>
</section>

resources/views/frontend/footer.blade.php
<footer class="footer">
    <div class="footer__wrapper ">
        <div class="footer__items">
            <div class="footer__items_item finish">
                <h3 class="finish_title">Получите купон на сумму 15 000 рублей!</h3>
                <p class="finish_info">Оставьте заявку и получите купон для бесплатного продвижения вашего сайта в течение месяца на сумму 15 000 рублей</p>
                <form-component button="Оставить заявку" tag="Купон"></form-component>
            </div>
        </div>
    </div>
    <div class="footer__wrapper bottom">
        <div class="footer__items">
            <div class="footer__items_item bottom__item bottom__logo">
                <img src="/img/logo_white.svg" alt="trend-p">
                <p class="copy">ООО “Trend Pro” © 2013—2020</p>
            </div>
            <div class="footer__items_item bottom__item bottom__office">
                <div class="bottom_label">Центральный офис</div>
                <div class="bottom_phone">
                    <a href="tel:88003332268">8 800 333-22-68</a>
                    <span>Круглосуточно | Бесплатно</span>
                </div>
                <p class="bottom_address">г. Москва, ул. Вятская, 70</p> 
                <a href="mailto:info@trend-p.ru" class="bottom_mail">info@trend-p.ru</a>
                <ul class="bottom_social">
                    <li><a href="" target="_blank"><img src="/img/social_inst.svg" alt="instagram"></a></li>
                    <li><a href="" target="_blank"><img src="/img/social_inst.svg" alt="instagram"></a></li>
                    <li><a href="" target="_blank"><img src="/img/social_inst.svg" alt="instagram"></a></li>
                    <li><a href="" target="_blank"><img src="/img/social_inst.svg" alt="instagram"></a></li>
                </ul>
                <p class="copy">ООО “Trend Pro” © 2013—2020</p>
            </div>
            <div class="footer__items_item bottom__item bottom__menu">
                <div class="bottom_label">Разделы</div>
                <ul class="bottom__nav">
                    <li class="bottom__nav_item active">Разработка</li>
                    <li class="bottom__nav_item"><a href="">Проекты</a></li>
                    <li class="bottom__nav_item"><a href="">Отзывы</a></li>
                    <li class="bottom__nav_item"><a href="">Контакты</a></li>
                </ul>
            </div>
            <div class="footer__items_item bottom__item bottom__hh">
                <div class="bottom_label">Вакансии</div>
                <ul class="bottom__nav">
                    <li class="bottom__nav_item"><a href="">Дизайнер</a></li>
                    <li class="bottom__nav_item"><a href="">Front-end разработчик</a></li>
                    <li class="bottom__nav_item"><a href="">Back-end разработчик</a></li>
                    <li class="bottom__nav_item"><a href="">Специалист по SEO и контекстной рекламме</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

resources/views/frontend/index.blade.php
@extends('layouts.site')


@section('header')
    

@endsection


@section('content')


@endsection


@section('footer')


@endsection